name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  phpunit:
    strategy:
      matrix:
        php-versions: [ '7.4' ]
    name: Run PHPUnit tests with PHP version ${{ matrix.php-versions }}
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Check PHP version
        run: php -v
      - name: Composer install
        run: composer install --prefer-install=dist --no-interaction --no-progress
      - name: Run tests
        run: vendor/bin/phpunit